server:
  port: 8080
eureka:
  instance:
    preferIpAddress: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: '*'
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: ms-cars
          uri: lb://ms-cars
          predicates:
            - Path=/cars/**
        - id: ms-prices
          uri: lb://ms-prices
          predicates:
            - Path=/prices/**
        - id: ms-repairs
          uri: lb://ms-repairs
          predicates:
            - Path=/repairs/**