server:
  port: 8092
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/repairs-db
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka